### ISSUE TITLE
Problem with dlls (32/64 bits)

### ISSUE THREAD

**Issue by mambrino** [tonyt73/AGDX-Studio#27]
In Windows 10 x64 it installs perfectly but when it starts it asks for 32-bit libraries, if it is launched from the launcher it asks for CC32C280MT.DLL and if it is launched from AGD Studio.exe it asks for XMLRTL280.BPL.

It seems that the 64-bit version is being installed but the launcher is for the 32-bit version or something similar.

This happens to me with any version of the new installer (>=0.12), with version 0.10 with the old installer it works without problems.

Greetings and thanks

**Comment by farfromsleep** [comment]
Just wanted to add I have the exact same issue here.

**Comment by farfromsleep** [comment]
Been messing with this and found a temp fix to get it working, at least until the issue is resolved. Installing the build prerequisites as mentioned in the readme will allow the latest version to seemingly run fine (this is my first time using it, but it seems fine). So installing the latest trial of RAD Studio and LMD-Tools from their download pages (I couldn't find "innovative components" there but the lmd-tools package seems to do the trick)

It's a little overkill to have to install a full dev environment, but like I said, it's just a quick fix. I'm guessing there are required packages included there that weren't bundled in the latest builds.

Also note that it won't work unless run via the launcher, running AGD Studio directly will throw an error. I hope that's a little helpful anyway!

**Comment by mambrino** [comment]
yes, it's a little overkill, but useful while issue is fixed. Thanks ;)

**Comment by tonyt73** [comment]
Great debugging and very helpful comments.
Thanks for helping with the issue.
There was a reference to the 32bit launcher in the 64bit installer.
